---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: curator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: curator-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: curator
        property: github-token
