---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguard-home-secret
    creationPolicy: Owner
  data:
    - secretKey: ADGUARD_ADMIN_USERNAME
      remoteRef:
        key: adguard-home
        property: admin-username
    - secretKey: ADGUARD_ADMIN_PASSWORD_HASH
      remoteRef:
        key: adguard-home
        property: admin-password-hash
