{
 "title": "SMART",
 "tags": [
  "autograf",
  "generated"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "smartctl-exporter" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(smart_status, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "available",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "available_spare",
   "type": "timeseries",
   "description": "Available spare",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "available_spare{job=~'$job',instance=~'$instance', device!~\"/dev/s.*\"}"
    }
   ]
  },
  {
   "title": "critical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "critical_warning",
   "type": "timeseries",
   "description": "Critical warning counter",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "critical_warning{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "media",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "media_errors",
   "type": "timeseries",
   "description": "Media errors counter",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "media_errors{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl-exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "smart_status",
   "type": "timeseries",
   "description": "Smart status",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smart_status{instance=~'$instance',job=~'$job'}"
    }
   ]
  },
  {
   "title": "smartctl",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "smartctl_version",
   "type": "timeseries",
   "description": "smartctl version",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_version{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "smartctl_device_percentage_used",
   "type": "timeseries",
   "description": "Device write percentage used",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_percentage_used{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_interface_speed",
   "type": "timeseries",
   "description": "Device interface speed, bits per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_interface_speed{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_available_spare",
   "type": "timeseries",
   "description": "Normalized percentage (0 to 100%) of the remaining spare capacity available",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_available_spare{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_status",
   "type": "timeseries",
   "description": "Device status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_status{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_temperature",
   "type": "timeseries",
   "description": "Device temperature celsius",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_smart_status",
   "type": "timeseries",
   "description": "General smart status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_power_on_seconds",
   "type": "timeseries",
   "description": "Device power on seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_power_on_seconds{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_power_cycle_count",
   "type": "timeseries",
   "description": "Device power cycle count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_power_cycle_count{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_num_err_log_entries",
   "type": "timeseries",
   "description": "Contains the number of Error Information log entries over the life of the controller",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_num_err_log_entries{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_block_size",
   "type": "timeseries",
   "description": "Device block size",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_block_size{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_smartctl_exit_status",
   "type": "timeseries",
   "description": "Exit status of smartctl on device",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_smartctl_exit_status{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_capacity_bytes",
   "type": "timeseries",
   "description": "Device capacity in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_bytes{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_capacity_blocks",
   "type": "timeseries",
   "description": "Device capacity in blocks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_blocks{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_attribute",
   "type": "timeseries",
   "description": "Device attributes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_attribute{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "smartctl_device_critical_warning",
   "type": "timeseries",
   "description": "This field indicates critical warnings for the state of the controller",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_critical_warning{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_media_errors",
   "type": "timeseries",
   "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_media_errors{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_bytes_written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_bytes_written{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  },
  {
   "title": "smartctl_device_bytes_read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_bytes_read{job=~'$job',instance=~'$instance'}[3m])"
    }
   ]
  }
 ]
}