---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./atuin/install.yaml
  - ./dashboard/install.yaml
  - ./gramps/install.yaml
  - ./immich/install.yaml
  - ./karakeep/install.yaml
  - ./miniflux/install.yaml
  - ./opencloud/install.yaml
  - ./radicale/install.yaml
components:
  - ../../components/namespace
  - ../../components/alerts
