---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo
        property: FORGEJO_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: forgejo
        property: FORGEJO_ADMIN_PASSWORD
    - secretKey: key
      remoteRef:
        key: forgejo
        property: FORGEJO_OAUTH_CLIENT_ID
    - secretKey: secret
      remoteRef:
        key: forgejo
        property: FORGEJO_OAUTH_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-gpg
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-gpg-key
    creationPolicy: Owner
  data:
    - secretKey: privateKey
      remoteRef:
        key: forgejo
        property: GPG_PRIVATE_KEY
