---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-lens
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguard-lens-secret
    creationPolicy: Owner
  data:
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: adguard-home
        property: admin-username
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: adguard-home
        property: admin-password
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: adguard-home
        property: unifi-api-key
