---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: FORGEJO_RUNNER_TOKEN
      remoteRef:
        key: forgejo
        property: FORGEJO_RUNNER_TOKEN
