---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-swap-models
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
